server {
    listen 80;
    listen [::]:80;
    server_name docs.zunialab.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name docs.zunialab.com;

    ssl_certificate     /etc/letsencrypt/live/zunialab.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zunialab.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    root /srv/zunia/repos/zunia-docs/build;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
